DROP TABLE IF EXISTS USER_TABLE CASCADE;
DROP TABLE IF EXISTS BILL_TABLE CASCADE;

CREATE TABLE USER_TABLE (
	USER_ID			INT PRIMARY KEY,
	USERNAME		VARCHAR(100) NOT NULL,
	EMAIL			VARCHAR(100) NOT NULL
);

CREATE TABLE BILL_TABLE (
	BILL_ID			INT PRIMARY KEY NOT NULL,
	BILLNUMBER		INT NOT NULL,
	BILLDATE		DATE,
	TOTAL			DECIMAL NOT NULL,
	USER_ID			INT REFERENCES USER_TABLE(USER_ID)
);